@echo off
set HUBOT_SLACK_TOKEN=xoxb-27292579361-I1avgjsPSMMk1A9V6k8nuHhB
set HUBOT_ANSWER_TO_THE_ULTIMATE_QUESTION_OF_LIFE_THE_UNIVERSE_AND_EVERYTHING=DISREGARD FEMBOTS, AQUIRE BITCOIN
set HUBOT_SLACK_INCOMING_WEBHOOK=https://hooks.slack.com/services/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
@echo on
bin\hubot --adapter slack